### ISSUE TITLE
Warmane 2.4.3 - Disconnection

### ISSUE THREAD

**Issue by Sp5rky** [fjaros/wowchat#1]
```
C:\Users\<User>\Downloads\wowchat>java -Dlogback.configurationFile=logback.xml -jar wowchat.jar wowchat.conf
22:51:53.232 INFO  n.d.jda.core.JDA - Login Successful!
22:51:54.327 INFO  n.d.j.c.r.WebSocketClient - Connected to WebSocket
22:51:55.077 INFO  n.d.jda.core.JDA - Finished Loading!
22:51:55.087 INFO  w.r.RealmConnector - Logging into realm server logon.warmane.com:3724
22:51:56.389 INFO  w.g.GameConnector - Logging into game server Outland (54.36.105.147:8085)
22:51:57.162 INFO  w.g.GameConnector - Disconnected from game server! Reconnecting in 10 seconds...
22:52:07.163 INFO  w.g.GameConnector - Logging into game server Outland (54.36.105.147:8085)
22:52:07.983 INFO  w.g.GameConnector - Disconnected from game server! Reconnecting in 10 seconds...
22:52:17.984 INFO  w.g.GameConnector - Logging into game server Outland (54.36.105.147:8085)
22:52:18.745 INFO  w.g.GameConnector - Disconnected from game server! Reconnecting in 10 seconds...
```

I've double checked the config for Warmane TBC server and made sure the discord token is correct.

```
wow {
  version=2.4.3
  realmlist=logon.warmane.com
  realm=Outland
  account=<User>
  password=<Pass>
  character=<Charname>
}
```

Tried from another machine in another location around the world but still comes up with the same error message.

**Comment by fjaros** [comment]
Yep. I actually had this issue during development as well. It is because Warmane 2.4.3 blocks connections from Mac clients. You can see more info [here](https://www.reddit.com/r/wowservers/comments/8ndjtz/has_the_243_macos_native_client_suddenly_started/). You will meet the same issue when trying to connect with a real Mac 2.4.3 client.

The bot emulates the Mac client because most servers don't have their own implementations for warden anti-cheat which makes the dev work much easier. Unfortunately to develop this to emulate Windows clients and correctly respond to each pserver's closed-source warden implementation would be quite challenging.

My best recommendation would be to petition these servers to allow Mac client connections or somehow else figure out how to support these non-malicious "bot" tools.
