### ISSUE TITLE
Does not work on Warmane

### ISSUE THREAD

**Issue by nerestaren** [fjaros/wowchat#104]
Hello.

Since a few days ago, this does not work on Warmane's Lordaeron.

```
INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
INFO  wowchat.WoWChat$ - Connecting to Discord...
INFO  n.d.jda.api.JDA - Login Successful!
INFO  n.d.j.i.r.WebSocketClient - Connected to WebSocket
INFO  n.d.jda.api.JDA - Finished Loading!
INFO  w.r.RealmConnector - Connecting to realm server logon.warmane.com:3724
WARN  i.n.u.i.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: <<<<REDACTED>>>>
INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Lordaeron
INFO  w.g.GameConnector - Connecting to game server Lordaeron (51.178.64.97:8091)
INFO  w.g.GamePacketHandlerWotLK - Connected! Authenticating...
INFO  w.g.GamePacketHandlerWotLK - Successfully logged in!
INFO  w.g.GamePacketHandlerWotLK - Warden handling initialized!
INFO  w.g.GamePacketHandlerWotLK - Logging in with character <<<<REDACTED>>>>
```

Can I do anything else to help you troubleshoot this?

Thank you.

**Comment by fjaros** [comment]
Looks like warmane changed something again (big surprise). They send the first "character list" packet which wowchat parses and tries to login with the character from config. Warmane now stopped acknowledging that attempt and instead a few seconds later sends another unsolicited character list packet. Wowchat ignores this one because it's already received one before and is waiting to be logged in.
The fix I'll make here is if we receive another character list packet but wowchat hasn't joined the world yet, we might as well try doing it again.

**Comment by fjaros** [comment]
Fixed by https://github.com/fjaros/wowchat/commit/7c8c20806f6ad8f827881aefbfb97d88a5685b94 . Please download the latest release zip file.
