### ISSUE TITLE
Warmane Onyxia realm character not found

### ISSUE THREAD

**Issue by superseyan101** [fjaros/wowchat#118]
Hi! When I tried to set this up for our guild chat, it does not detect any characters on Warmane's Onyxia realm. Tried the Icecrown realm and it works. I suspect it might be because the Onyxia realm is a progressive realm (currently in Vanilla phase 4) and it uses the same client as Icecrown (3.3.5). 

![image](https://github.com/fjaros/wowchat/assets/90171371/c22ea141-9ce0-489c-b501-1e04a7bc0e1a)

**Comment by fjaros** [comment]
Yeah, it turns out on "Onyxia" realm, when you request the character list with Mac platform, it will send back the list with the strings "Mac OSX" "Not supported" "Use Wine" "Or Windows" .. so wowchat is not able to find your character name in the list.
Unfortunately switching to platform=Windows means having to answer to warden, which wowchat is unable to do and so it will be kicked off by the server in 30 seconds after login.
Sorry, doesn't look like it will work on this realm.
