### ISSUE TITLE
Achievement issue

### ISSUE THREAD

**Issue by Bennylavaa** [fjaros/wowchat#120]
Getting a parsing error or something in Discord with achievements when someone earns one

Totembringer has earned the achievement [[5012]](http://wotlk-twinhead.twinstar.cz/?achievement=5012)!

However when they link that same achievement in chat it looks like this:

[Totembringer]:  [[Broodmother's Lair]](http://wotlk-twinhead.twinstar.cz/?achievement=5012)

I understand this is a custom quest and I have added it to the achivements.csv here https://github.com/Bennylavaa/wowchat-epoch/blob/main/src/main/resources/achievements.csv 

This is my config as well 
`  achievement {
    enabled=1
    format="%user has earned the achievement %achievement!"`

I have this repo going because its a custom server. 

It seems to only affect the messages put in guild chat when you unlock the achievement. 

Any ideas?

**Comment by fjaros** [comment]
Did you recompile the project and start it again with the new jar?

**Comment by Bennylavaa** [comment]
Yes I did

**Comment by fjaros** [comment]
Can you upload your compiled jar here or give me a link?

**Comment by Bennylavaa** [comment]
https://github.com/Bennylavaa/wowchat-epoch/releases/tag/1.03

should be here

**Comment by Bennylavaa** [comment]
[wowchat.zip](https://github.com/fjaros/wowchat/files/15085125/wowchat.zip)

**Comment by Bennylavaa** [comment]
What I am not understanding if linked the achievement text is put into chat. However, the guild announcement sends an id instead of the achievement text.

**Comment by fjaros** [comment]
yeah it's because linking in the chat actually sends the achievement name in the message itself so wowchat parses that from the message and displays it. in the case of guild notification, we only get the ID hence why we need a text file to look up the name of that ID. https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/MessageResolver.scala#L43

As you see, the fallback if the ID is not found is to just return the ID as the name. So it looks like the lookup is failing. But it seems that your achievements.csv is correct and also you recompiled it into the jar so the lookup should be succeeding.

So I don't know what's up. You'll need to debug the content of the GameResources.ACHIEVEMENT map.

**Comment by Bennylavaa** [comment]
alright, I also just noticed that the chatbot doesnt log the guild announcement achievement in its log, it just logs the linked ones.

**Comment by Bennylavaa** [comment]
actually this might break it

`247,Make Love, Not Warcraft`

**Comment by Bennylavaa** [comment]
would make sense why some work and others dont, could be that everything below that gets wonked out.

**Comment by Bennylavaa** [comment]
there are a few achievements with commas in their names.

**Comment by fjaros** [comment]
That's okay and expected: https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GameResources.scala#L16
