### ISSUE TITLE
Discord Markup

### ISSUE THREAD

**Issue by pogonomic** [fjaros/wowchat#20]
Noticed a minor issue in the new version. (confirmed working in 1.2.10)
Using some Discord markup within the wowchat.conf but it's no longer working:

```
chat {
  channels=[
    {
      direction=both
      wow {
        type=Guild
        format="[%user]: %message"
      }
      discord {
        channel=guild-chat
        format="[**%user**]: %message"         <------------ Make username bold in Discord
      }
    }
```

Shows up in Discord with the asterisks showing.

**Comment by fjaros** [comment]
Ah. I broke this with https://github.com/fjaros/wowchat/commit/26a9bbfc5d796cea5c0a31936962f4ed5cc313b8 . Because there were characters being pasted in WoW chat which resulted in formatting being unintentionally applied to discord messages.

I will change this code to apply the escaping before the formatting from config.

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/8235797f71a7cdcb10e410d4d694685ebc9e53d7 . Re-download the release :)
