### ISSUE TITLE
Filter not working for Green System Messages

### ISSUE THREAD

**Issue by virtualbjorn** [fjaros/wowchat#35]
Unable to filter messages in Green color
![image](https://user-images.githubusercontent.com/19782129/93612254-e14c3280-fa01-11ea-9929-28374cfc7cad.png)
`Players can now make use of an opt-in feature: Mercenary Mode that allows you to briefly forget your faction allegiance and fight for the enemy. This feature can be toggled within the account settings on the website.`

Able to filter Yellow System messages only the green system messages aren't filtered.
Here's my filter setup
![image](https://user-images.githubusercontent.com/19782129/93612647-515ab880-fa02-11ea-835e-3ae8f409fe1d.png)

**Comment by virtualbjorn** [comment]
I did some debugging and here's what I found
![image](https://user-images.githubusercontent.com/19782129/93623903-0779ce80-fa12-11ea-82b9-96f31bb7fac5.png)
1st log is for `parsedLinks`
2nd log is for `parsedResolvedTags`
3rd log is for `message`
![image](https://user-images.githubusercontent.com/19782129/93624040-4445c580-fa12-11ea-9f9b-7173ef3b5a7e.png)
From these lines we're passing in a raw message instead of the parsed ones.

**Comment by fjaros** [comment]
Hey there. Yep this is known behavior. At the time I was thinking that it might be unclear if there is some post-processing done on the bot (such as translating Discord @name tags and emojis and links) that might cause filters to be missed or wrongly applied. I thought it might be a better user experience to do it on the original message.
Of course, I missed the part where messages can contain colors and things like that which will be unclear to the user on both wow and Discord since the bot removes such things before posing the message to Discord.

I agree the user experience is bad and filtering probably should be done on the post-processed message rather than the original. Thankfully it's an easy change.

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/c3a4af0f264227b402b51e32bd3bc06a435c127d
