### ISSUE TITLE
Mists of Pandaria 18019

### ISSUE THREAD

**Issue by rodrigoolvs** [fjaros/wowchat#37]
**Hello, I'm trying to connect Wowchat to Mists of Pandaria 18019, but the version error is invalid.**

**I would like help to make it work on Build 18019.**
**Waiting for answers...**

**Comment by fjaros** [comment]
Sorry, that won't work. The only MoP build supported is 18414 (version 5.4.8hotfix1). To be more specific, this is the build that was deployed to Tauri WoW whenever I did the development 2 years ago.

It might seem like a simple fix as 18019 and 18414 are very similar, but unfortunately it is not so. Since Cataclysm, blizzard pretty severely changes/obfuscates the network code to deter bots, so it would take quite a bit of work to support 18019. You would have to write a version of  https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePacketHandlerMoP18414.scala to support it.
