### ISSUE TITLE
Problem with Russian symbols

### ISSUE THREAD

**Issue by ForesterDev** [fjaros/wowchat#5]
Hello. I found problem with Russian symbols.

In Game:
![g1](https://user-images.githubusercontent.com/11771800/49434586-eceb4c80-f7cd-11e8-81a5-0ef622d8b25c.png)

In discord:
![discord](https://user-images.githubusercontent.com/11771800/49434593-f1b00080-f7cd-11e8-9192-5af05b1eab1a.png)

The problem is only with chat text, name of users is ok

**Comment by fjaros** [comment]
It actually works for me, but I think it is due to the bot trying to use something else than UTF-8 encoding for messages on your computer. I've changed the code to always use UTF-8. Please try to redownload the release and see if it works now.
![image](https://user-images.githubusercontent.com/541364/49500741-3d8e9400-f826-11e8-9a31-650b7ea6850f.png)

**Comment by ForesterDev** [comment]
Now all is ok. Ty
![21231](https://user-images.githubusercontent.com/11771800/49517471-b426a280-f8b5-11e8-9a34-e87b9161448e.png)
