### ISSUE TITLE
Unable to proceed from realm connection

### ISSUE THREAD

**Issue by virtualbjorn** [fjaros/wowchat#50]
![image](https://user-images.githubusercontent.com/19782129/99525250-88365600-29d4-11eb-96de-5df6ae2a3a5b.png)

My bot can no longer proceed to character selection after logging in. This happened since 2 days ago.
I updated to 1.3.6 still the same. I'm using the same config as I had before.

Also, my bot account is banned. Managed to login using the wow wotlk client.

Any idea how this happened?

**Comment by Bezrayer** [comment]
Have the same problem. Bot account is NOT banned everything is the same like it was. 

![Výstřižek2](https://user-images.githubusercontent.com/74709477/99650408-ad1edd80-2a55-11eb-9775-747e45197537.PNG)

**Comment by fjaros** [comment]
I looked into this - the reason is because warmane seems to have broken/disabled login with platform Mac onto their realm. They had the same thing in place for their TBC realm and I guess they introduced it into WotLK as well. See https://github.com/fjaros/wowchat/issues/1

Sorry there is nothing I can do about this :(

**Comment by fjaros** [comment]
Added explicit message in https://github.com/fjaros/wowchat/commit/f9fef8930ee5afdc41ca3054982cb9b1349396af

**Comment by virtualbjorn** [comment]
Thanks for the update. It was working fine but maybe they updated their server side authentication for WoTLK. It was a great to get to know this project.

**Comment by fjaros** [comment]
> Thanks for the update. It was working fine but maybe they updated their server side authentication for WoTLK. It was a great to get to know this project.

Sure. Just to be clear, they DID update their server side authentication to reject Mac logins on purpose. Their system response is malformed so the bot was not displaying the rejection properly. I fixed this in the above commit.

**Comment by fjaros** [comment]
This is fixed actually.

**Comment by fjaros** [comment]
hi folks. good news! i actually found an error in my code that has been
there since the beginning. warmane recently changed things on their side to
start checking for the values being produced by this error and that's why
login was rejected. the bot should work again in the new release.

út 24. 11. 2020 v 2:34 odesílatel virtualbjorn <notifications@github.com>
napsal:
