### ISSUE TITLE
error login character

### ISSUE THREAD

**Issue by AkbarSubastian** [fjaros/wowchat#51]
hello,
there is error when logging with character, im already using 1.3.6 version on server warmane 3.3.5.
screenshot attached.

thanks
![error](https://user-images.githubusercontent.com/73558605/101243715-a7ebaf00-3734-11eb-8d70-afa4d946561d.jpg)

**Comment by virtualbjorn** [comment]
Hi, @AkbarSubastian , were you able to authenticate to Warmane WOTLK servers?

**Comment by virtualbjorn** [comment]
Warmane must have disable mac logins for their wotlk client same with their tbc client.

**Comment by fjaros** [comment]
Note that although you fixed the typo, the bot will not work on Warmane because they block logins from Mac clients. See https://github.com/fjaros/wowchat/issues/50

**Comment by fjaros** [comment]
hi folks. good news! i actually found an error in my code that has been
there since the beginning. warmane recently changed things on their side to
start checking for the values being produced by this error and that's why
login was rejected. the bot should work again in the new release.

so 5. 12. 2020 v 5:21 odesílatel virtualbjorn <notifications@github.com>
napsal:

**Comment by fjaros** [comment]
Fixed in release v1.3.7 for build 3.3.5.
