### ISSUE TITLE
More of a question then an issue...

### ISSUE THREAD

**Issue by MKScorp** [fjaros/wowchat#62]
Hello,

First of all, I love your work on this. It has made my friends and I very content with having the ability to chat from within the game to the discord channels. Thank you for all your hard work! I know it's not easy :)

I was wondering if there was a way to have the chat bot work under BFA 8.3.7? If there is, please let me know, it would be greatly appreciated.

Have a great day.

**Comment by fjaros** [comment]
Thanks for the kind words. Unfortunately there is no way to have the bot work on any versions outside of the ones specifically implemented. For Vanilla -> WotLK it was easier to be cross compatible, like you might be able to have WotLK 3.3.5 work with 3.3.3 for example.
However since 4.0 (Cataclysm), the communication protocol for the game is obfuscated to be vastly different between each build. In order to support any build since 4.0 forward, you have to implement basically all functions of how the bot talks to the game for your specific target build. I've gone through the pain of doing that for the last Cataclysm build (15595) and the last MoP build (18414).
I'm not interested in going thorough that work again for any future builds, since as you might imagine it only gets more and more complex. Sorry! Someone else will have to pick up that torch.
