### ISSUE TITLE
Cannot connect to Authentication servers Error code 0E Ascension wow

### ISSUE THREAD

**Issue by Gnarls666** [fjaros/wowchat#68]
![image](https://user-images.githubusercontent.com/99755274/154870933-0c08f6e6-85c2-4817-83ab-e20321175f8a.png)
everthything works until it tries to connect to ascension wows auth server

**Comment by fjaros** [comment]
Hey. I believe this is because Ascension does not allow logins from platform Mac. try to use platform=Windows in your config. The bot will complain about this with a "warden on windows is not supported" message. However unless ascension team changed something, I don't think they disconnect you for this like other servers . At least this is what I remember from ~2 years ago.

**Comment by Gnarls666** [comment]
Thank you very much i feel like a dummy for not trying that. it works perfectly now <3
